backend/controllers/AlbumController.php
<?php

namespace backend\controllers;

use blog\forms\manage\album\AlbumEditForm;
use blog\helpers\AlbumHelper;
use yii\web\NotFoundHttpException;
use backend\forms\AlbumSearchForm;
use blog\entities\Album;
use blog\manage\AlbumManageService;
use yii\web\Controller;
use blog\forms\manage\album\AlbumCreateForm;
use \Yii;
use yii\filters\VerbFilter;

class AlbumController extends Controller
{

	private $service;

	public function __construct( $id, $module, array $config = [], AlbumManageService $service)
	{
		$this->service = $service;
		parent::__construct( $id, $module, $config );
	}

	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * @param $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model not found
	 */
	public function actionUpdate($id)
	{
		$album = $this->findModel($id);

		$form = new AlbumEditForm($album);
		if ($form->load(Yii::$app->request->post()) && $form->validate()){
			try{
				$this->service->edit($album->id, $form);
				Yii::$app->session->setFlash('success', 'Album updated');
				return $this->redirect(['view', 'id' => $id]);
			}catch (\DomainException $e){
				Yii::$app->errorHandler->logException($e);
				Yii::$app->session->setFlash('error', $e->getMessage());
			}
		}

		return $this->render('update',
			[
				'model' => $form,
				'album' => $album
			]);
	}

	/**
	 * @param $id
	 *
	 * @return mixed
	 */
	public function actionView($id)
	{
		$model = $this->findModel($id);
		return $this->render('view', [
			'model' => $model,
		]);
	}

	/**
	 * @return mixed
	 */
	public function actionCreate()
	{
		$form = new AlbumCreateForm();
		if ($form->load(Yii::$app->request->post()) && $form->validate()){
			try{
				$album = $this->service->create($form);
				Yii::$app->session->setFlash('success', 'Album created');
				return $this->redirect(['view', 'id' => $album->id]);
			}catch (\RuntimeException $e){
				Yii::$app->errorHandler->logException($e);
				Yii::$app->session->setFlash('error', $e->getMessage());
			}
		}

		return $this->render('create', ['model' => $form]);
	}

	/**
	 * 1234
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new AlbumSearchForm();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * @param $id
	 *
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$photos = AlbumHelper::getPhotos($id);
		foreach ($photos as $photo){
			$photo->delete();
		}
		$this->findModel($id)->delete();
		return $this->redirect(['index']);
	}

	/**
	 * @param $id
	 * @return Album the loaded model
	 * @throws NotFoundHttpException
	 */
	protected function findModel($id)
	{
		if (($model = Album::findOne($id)) !== null){
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

backend/controllers/CPlanController.php
<?php

namespace backend\controllers;

use blog\forms\manage\competition\CplanCreateForm;
use blog\forms\manage\competition\CplanEditForm;
use blog\manage\competition\CPlanManageService;
use Yii;
use blog\entities\competition\CPlan;
use backend\forms\CPlanSearchForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CPlanController implements the CRUD actions for CPlan model.
 */
class CplanController extends Controller
{
	private $service;

	public function __construct( $id, $module, array $config = [], CPlanManageService $service )
	{
		$this->service = $service;
		parent::__construct( $id, $module, $config );
	}

	/**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CPlan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CPlanSearchForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CPlan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CPlan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new CplanCreateForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        	try{
        		$c_plan = $this->service->create($form);
        		Yii::$app->session->setFlash('success', 'Календарный план создан');
        		return $this->redirect(['view', 'id' => $c_plan->id]);
	        }catch(\RuntimeException $e){
				Yii::$app->errorHandler->logException($e);
				Yii::$app->session->setFlash('error', $e->getMessage());
	        }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing CPlan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $cplan = $this->findModel($id);
        $form = new CplanEditForm($cplan);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        	try{
        		$this->service->edit($id, $form);
        		Yii::$app->session->setFlash('success', 'Календарный план изменен');
        		return $this->redirect(['view', 'id' => $id]);
	        }catch (\RuntimeException $e){
        		Yii::$app->errorHandler->logException($e);
        		Yii::$app->session->setFlash('error', $e->getMessage());
	        }
            return $this->redirect(['view', 'id' => $form->id]);
        }

        return $this->render('update', [
            'model' => $form,
	        'cplan' => $cplan
        ]);
    }

    /**
     * Deletes an existing CPlan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CPlan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CPlan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CPlan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use blog\forms\manage\Post\PostCreateForm;
use blog\forms\manage\Post\PostEditForm;
use blog\manage\PostManageService;
use Yii;
use blog\entities\Post;
use backend\forms\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
	private $service;

	public function __construct( $id, $module, array $config = [], PostManageService $service )
	{
		$this->service = $service;
		parent::__construct( $id, $module, $config );
	}

	/**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new PostCreateForm();
		$userId = Yii::$app->user->getId();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        	try{
        		$post = $this->service->create($form, $userId);
        		Yii::$app->session->setFlash('success', 'Статься успешно создана');
		        return $this->redirect(['view', 'id' => $post->id]);
	        }catch (\RuntimeException $e){
        		Yii::$app->errorHandler->logException($e);
        		Yii::$app->session->setFlash('error', $e->getMessage());
	        }

        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $post = $this->findModel($id);
        $form = new PostEditForm($post);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        	try {
        		$this->service->edit($form, $id);
        		Yii::$app->session->setFlash('success', 'Статья успешно изменена');
		        return $this->redirect(['view', 'id' => $id]);
	        }catch (\RuntimeException $e){
        		Yii::$app->errorHandler->logException($e);
        		Yii::$app->session->setFlash('error', $e->getMessage());
	        }

        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use blog\forms\manage\User\UserCreateForm;
use blog\forms\manage\User\UserEditForm;
use Yii;
use blog\entities\User\User;
use backend\forms\UserSearchForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use blog\manage\UserManageService;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
	private $service;

	public function __construct( $id, $module, array $config = [], UserManageService $service ) {
		$this->service = $service;
		parent::__construct( $id, $module, $config );
	}

	/**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearchForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new UserCreateForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try{
				$user = $this->service->create($form);
				$this->redirect(['view', 'id' => $user->id]);
            }catch (\DomainException $e){
            	Yii::$app->errorHandler->logException($e);
            	Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        $form = new UserEditForm($user);
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
        	try{
        		$this->service->edit($user->id, $form);
		        return $this->redirect(['view', 'id' => $user->id]);
	        }catch (\DomainException $e){
        		Yii::$app->errorHandler->logException($e);
        		Yii::$app->session->setFlash('error', $e->getMessage());
	        }

        }

        return $this->render('update', [
            'model' => $form,
	        'user' => $user,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;
?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>


    </nav>
</header>

backend/views/layouts/left.php
<?php if (Yii::$app->user->can('admin')):?>
    <aside class="main-sidebar">

        <section class="sidebar">

                <?= dmstr\widgets\Menu::widget(
                    [
                        'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                        'items' => [
                            ['label' => 'Управление', 'options' => ['class' => 'header']],
                            ['label' => 'Пользователи', 'url' => ['/user/index'], 'active' => $this->context->id == 'user', 'icon' => 'user'],
                            ['label' => 'Фотографии', 'url' => ['/photo/index'], 'active' => $this->context->id == 'photo'],
                            ['label' => 'Фотоальбомы', 'url' => ['/album/index'], 'active' => $this->context->id == 'album'],
                            ['label' => 'Видео', 'url' => ['/video/index'], 'active' => $this->context->id == 'video'],
                            ['label' => 'Документы', 'url' => ['/document/index'], 'active' => $this->context->id == 'document'],
                            ['label' => 'Календарные планы', 'url' => ['/cplan/index'], 'active' => $this->context->id == 'cplan'],
                            ['label' => 'Положения', 'url' => ['/provision/index'], 'active' => $this->context->id == 'provision'],
                            ['label' => 'Результаты', 'url' => ['/result/index'], 'active' => $this->context->id == 'result'],
                            ['label' => 'Статьи', 'url' => ['/post/index'], 'active' => $this->context->id == 'post'],
                            ['label' => 'Комментарии', 'url' => ['/comment/index'], 'active' => $this->context->id == 'comment'],
                        ],
                    ]
                ) ?>

        </section>

    </aside>
<?php endif;?>

backend/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


backend\assets\AppAsset::register($this);

dmstr\web\AdminLteAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render(
        'header.php',
        ['directoryAsset' => $directoryAsset]
    ) ?>

    <?= $this->render(
        'left.php',
        ['directoryAsset' => $directoryAsset]
    )
    ?>

    <?= $this->render(
        'content.php',
        ['content' => $content, 'directoryAsset' => $directoryAsset]
    ) ?>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>